name: Build Windows and Linux

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    tags:
      - 'v*'  # Triggers on version tags

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            output_name: IPSWCompare.exe
            artifact_name: IPSWCompare-Windows.exe
          - os: ubuntu-latest
            output_name: IPSWCompare.AppImage
            artifact_name: IPSWCompare-Linux.AppImage

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow requests

    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --name IPSWCompare `
          --windowed `
          --icon app_icon.icns `
          --add-data "app_icon.icns;." `
          --add-data "forest-dark.tcl;." `
          --add-data "forest-dark;forest-dark" `
          --hidden-import PIL `
          --hidden-import PIL._tkinter_finder `
          ipsw_firmware_tool.py

    - name: Build Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        pyinstaller --name IPSWCompare \
          --windowed \
          --icon app_icon.icns \
          --add-data "app_icon.icns:." \
          --add-data "forest-dark.tcl:." \
          --add-data "forest-dark:forest-dark" \
          --hidden-import PIL \
          --hidden-import PIL._tkinter_finder \
          ipsw_firmware_tool.py
        
        # Create AppDir structure
        mkdir -p AppDir/usr/bin
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
        
        # Copy files
        cp -r dist/IPSWCompare/* AppDir/usr/bin/
        cp app_icon.icns AppDir/usr/share/icons/hicolor/256x256/apps/ipswcompare.png
        
        # Create desktop entry
        cat > AppDir/usr/share/applications/ipswcompare.desktop << EOF
        [Desktop Entry]
        Name=IPSW Firmware Comparison Tool
        Exec=IPSWCompare
        Icon=ipswcompare
        Type=Application
        Categories=Development;
        EOF
        
        # Get AppImage tool and make executable
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage
        
        # Create AppImage
        ./appimagetool-x86_64.AppImage AppDir IPSWCompare.AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/IPSWCompare/${{ matrix.output_name }}
          *.AppImage

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/IPSWCompare/${{ matrix.output_name }}
          *.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
