name: Build Executables

on:
  push:
    branches:
      - master  # Trigger on push to 'master' branch
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow requests  # Install required libraries

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --add-data "resources;resources" ipsw_firmware_tool.py
          mv dist/ipsw_firmware_tool.exe ./

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ipsw_firmware_tool_windows.exe
          path: ipsw_firmware_tool.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install pyinstaller pillow requests  # Install required libraries

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --add-data "resources:resources" ipsw_firmware_tool.py
          mv dist/ipsw_firmware_tool ./

      - name: Create AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mv ipsw_firmware_tool AppDir/usr/bin/
          wget -O appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool
          ./appimagetool AppDir ipsw_firmware_tool.AppImage

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ipsw_firmware_tool_linux.AppImage
          path: ipsw_firmware_tool.AppImage
